const language = {
    en: {
        Home: "Home",
        Shorts: "Shorts",
        Subscriptions: "Subscriptions",
        History: "History",
        YourVideos: "Your Videos",
        watchLater: "Watch Later",
        likedVideos: "Liked Videos",
        playlists: "Playlists",
        search: "Search",
        categories: [
            "All",
            "Music",
            "Live",
            "Gaming",
            "News",
            "Movies",
            "Cricket",
            "Technology",
            "Recently Uploaded",
            "JavaScript",
            "Programming",
            "Web Development",
            "React",
            "Node.js",
            "AI & Machine Learning",
            "Podcasts",
            "Education",
            "Comedy",
            "Trailers",
            "Short Films",
            "Vlogs",
            "Fitness",
            "Motivation",
            "Startups",
            "Finance",
        ]


    },
    hindi: {
        Home: "घर",
        Shorts: "शॉर्ट्स",
        Subscriptions: "सदस्यता",
        History: "इतिहास",
        YourVideos: "आपके वीडियो",
        watchLater: "बाद में देखें",
        likedVideos: "पसंदीदा वीडियो",
        playlists: "प्लेलिस्ट",
        search: "खोजें",
        categories: [
            "सभी",
            "संगीत",
            "लाइव",
            "गेमिंग",
            "समाचार",
            "फिल्में",
            "क्रिकेट",
            "टेक्नोलॉजी",
            "हाल ही में अपलोड",
            "जावास्क्रिप्ट",
            "प्रोग्रामिंग",
            "वेब डेवलपमेंट",
            "रिएक्ट",
            "नोड.js",
            "एआई और मशीन लर्निंग",
            "पॉडकास्ट",
            "शिक्षा",
            "कॉमेडी",
            "ट्रेलर",
            "शॉर्ट फिल्में",
            "व्लॉग्स",
            "फिटनेस",
            "प्रेरणा",
            "स्टार्टअप्स",
            "फाइनेंस",
        ]

    }
}
export default language